### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by bbangsik13** [BoMingZhao/GaussianPrediction#2]
Hi,

Thank you for the great work. I have some questions as follows:

1) In Table A, is `motion extrapolation` the same as `motion prediction` in Table 1?
2) On the project page, are the `Hyper-NeRF Dataset Prediction Results` all within the [0.8,1.0] range? The videos of scenes with different lengths are concatenated, which makes it confusing. 🥲

Thanks in advance for your help!

**Comment by BoMingZhao** [comment]
Hi,
Thanks for your interest in our work. 

1. Yes, ```motion extrapolation```  and ```motion prediction``` are the same.
2. In the paper, since the ground truth data is only available in the range [0-1], we train our model using the subset [0-0.8] and use the remaining [0.8-1] range for evaluation. However, on the project page, in order to display clearer prediction results, we extrapolate many more frames, although the training still uses the [0-0.8] range.

Hope these answer your questions.

**Comment by bbangsik13** [comment]
I see, thanks a lot for your help! 👍
